```{r }
# ローカル線形トレンドモデル
# ローカルレベルモデル +トレンド
```

```{r }
library(dlm)
knitr::opts_chunk$set(dev = "cairo_pdf", dev.args = list(family = "ipaexg"))
```

```{r }
# 季節成分とトレンド両方がありそうなデータとして、AirPassengersというデータを利用
# もともとのデータを対数変換したものを解析の対象とする
data <- log(AirPassengers)
# 　1959年以降を切り落とす
test.data <- window(data, end = c(1958, 12))

# 　Step1
# 　モデル作成のための関数を作る
build.1 <- function(theta) {
  dlmModPoly(
    order = 2,
    dV = exp(theta[1]),
    dW = c(exp(theta[2]), exp(theta[3]))
  ) +
    dlmModSeas(
      fr = 12,
      dW = c(theta[4], rep(0, 10)),
      dV = 0
    )
}

# 　Step2
# 　MLEでパラメタ推定。
fit.1 <- dlmMLE(
  test.data,
  parm = dlmMLE(
    test.data,
    parm = c(0, 1, 1, 1),
    build.1,
    method = "Nelder-Mead"
  )$par,
  build.1,
  method = "BFGS"
)

# 推定されたパラメタを使ってモデルを作り直す
DLM.1 <- build.1(fit.1$par)

# Step3
# カルマンフィルター
Filt.1 <- dlmFilter(test.data, DLM.1)

# Step4
# スムージング
Smooth.1 <- dlmSmooth(Filt.1)


plot(test.data,
  col = 1,
  type = "o",
  lwd = 1
)
lines(dropFirst(Filt.1$m)[, 1] + dropFirst(Filt.1$m)[, 3],
  col = 2,
  lwd = 2
)
lines(dropFirst(Smooth.1$s)[, 1] + dropFirst(Smooth.1$s)[, 3],
  col = 4,
  lwd = 2
)

legend(
  "bottomright",
  pch = c(1, NA, NA),
  col = c(1, 2, 4),
  lwd = c(1, 2, 2),
  legend = c("data", "Filter", "Smooth")
)
```

季節、トレンドなどを別々に表示

```{r }
par(mfrow = c(3, 1))
# 　元データ
plot(data,
  col = 1,
  type = "o",
  main = "data"
)
# 　レベル＋トレンド成分
plot(dropFirst(Smooth.1$s)[, 1], col = 4, main = "level+trend")
# 季節成分
plot(dropFirst(Smooth.1$s)[, 3], col = 4, main = "seasonal")
par(mfrow = c(1, 1))
```

予測

```{r }
Fore <- dlmForecast(Filt.1, nAhead = 24, sampleNew = 5)

# 　予測の答え合わせ
plot(data, type = "o")
lines(dropFirst(Smooth.1$s)[, 1] + dropFirst(Smooth.1$s)[, 3], col = 4)
lines(Fore$f, col = 2, lwd = 2)

legend(
  "bottomright",
  pch = c(1, NA),
  col = c(1, 2),
  lwd = c(1, 2),
  legend = c("実測値", "予測値")
)
```

乱数を使って予測

```{r }
Line <- function(x) {
  lines(x, col = 8, type = "o")
}

plot(
  window(test.data, start = c(1957, 1)),
  xlim = c(1957, 1961),
  ylim = c(5.7, 6.5),
  type = "o"
)
lapply(Fore$newObs, Line) # 乱数を使った予測値
lines(window(data, start = c(1959, 1)), col = 1, lwd = 2) # 実測値
lines(Fore$f, col = 2) # 予測値
legend(
  "topleft",
  pch = c(NA, NA, 1),
  col = c(1, 2, 8),
  lwd = c(2, 1, 1),
  legend = c("実測値", "予測値", "乱数を使った予測値")
)
```
